// <auto-generated />
using System;
using IFCStructuralAnalyzer.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IFCStructuralAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(IFCAnalyzerDbContext))]
    [Migration("20260119210751_RemoveUniqueGlobalIdIndex")]
    partial class RemoveUniqueGlobalIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CompressiveStrength")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<double>("Density")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Materials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Concrete",
                            CompressiveStrength = 30.0,
                            Density = 2500.0,
                            Name = "C30/37 Concrete"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Concrete",
                            CompressiveStrength = 35.0,
                            Density = 2500.0,
                            Name = "C35/45 Concrete"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Steel",
                            CompressiveStrength = 420.0,
                            Density = 7850.0,
                            Name = "S420 Steel"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Steel",
                            CompressiveStrength = 500.0,
                            Density = 7850.0,
                            Name = "S500 Steel"
                        });
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.StructuralElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Depth")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Height")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<string>("IFCType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("LocationX")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double>("LocationY")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<double>("LocationZ")
                        .HasPrecision(18, 6)
                        .HasColumnType("float(18)");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Width")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.HasKey("Id");

                    b.HasIndex("FloorLevel");

                    b.HasIndex("GlobalId")
                        .IsUnique();

                    b.HasIndex("IFCType");

                    b.HasIndex("MaterialId");

                    b.ToTable("StructuralElements", (string)null);

                    b.HasDiscriminator<string>("ElementType").HasValue("StructuralElement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.StructuralBeam", b =>
                {
                    b.HasBaseType("IFCStructuralAnalyzer.Domain.Entities.StructuralElement");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Beam");
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.StructuralColumn", b =>
                {
                    b.HasBaseType("IFCStructuralAnalyzer.Domain.Entities.StructuralElement");

                    b.HasDiscriminator().HasValue("Column");
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.StructuralSlab", b =>
                {
                    b.HasBaseType("IFCStructuralAnalyzer.Domain.Entities.StructuralElement");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Slab");
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.StructuralElement", b =>
                {
                    b.HasOne("IFCStructuralAnalyzer.Domain.Entities.Material", "Material")
                        .WithMany("StructuralElements")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");
                });

            modelBuilder.Entity("IFCStructuralAnalyzer.Domain.Entities.Material", b =>
                {
                    b.Navigation("StructuralElements");
                });
#pragma warning restore 612, 618
        }
    }
}
